config/routes.rb
Rails.application.routes.draw do

  root to: 'shopping_lists#index'

  resources :shopping_lists do
    resources :items
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
    belongs_to :shopping_list
end

app/models/shopping_list.rb
class ShoppingList < ActiveRecord::Base
    has_many :items, dependent: :destroy
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end
    
  def show
    @item = Item.find_by_id(params[:id])
  end
  
  def new
    # @item = Item.new
    @shopping_list = ShoppingList.find(params[:shopping_list_id])
    @item = @shopping_list.items.build
  end

  def edit
    @item = Items.find(params[:id])
  end
  
  def create
    @shopping_list = ShoppingList.find(params[:shopping_list_id])
    @item = @shopping_list.items.create(item_params)
    
    if @item.save
      redirect_to shopping_list_path(@shopping_list)
    else
      render 'new'
    end
  end
  
  def update
    @shopping_list = ShoppingList.find(params[:shopping_list_id])
    @item = Item.find(params[:id])
    
    if @item.update(item_params)
      redirect_to shopping_list_path(@shopping_list)
    else
      render 'edit'
    end
  end
  
  def destroy
    @shopping_list = ShoppingList.find(params[:shopping_list_id])
    @item = Item.find(params[:id])
    
    @item.destroy
    
    redirect_to shopping_list_path(@shopping_list)
  end
  
  private
    def item_params
      params.require(:item).permit(:name, :description, :quantity, :shopping_list_id)
    end
    
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
    
  def index
    @shopping_lists = ShoppingList.all
  end
    
  def show
    @shopping_list = ShoppingList.find_by_id(params[:id])
    
    gon.testVariable = Item.all
  end
  
  def new
    @shopping_list = ShoppingList.new
  end

  def edit
    @shopping_list = ShoppingList.find(params[:id])
  end
  
  def create
    @shopping_list = ShoppingList.new(shopping_list_params)
    
    if @shopping_list.save
      redirect_to @shopping_list
    else
      render 'new'
    end
  end
  
  def update
    @shopping_list =  ShoppingList.find(params[:id])
    
    if @shopping_list.update(shopping_list_params)
      redirect_to @shopping_list
    else
      render 'edit'
    end
  end
  
  def destroy
    @shopping_list = ShoppingList.find(params[:id])
    @shopping_list.destroy
    
    redirect_to shopping_lists_path
  end
  
  private
    def shopping_list_params
      params.require(:shopping_list).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/items/_item_form.html.erb
<%= form_for [@shopping_list, @item] do |f| %>
 
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %> prohibited
        this list from being saved:
      </h2>
      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
 <p>
   <%= f.label :quantity %><br>
   <%= f.number_field :quantity %>
 </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/items/new.html.erb
<div class="container">
    <h2>New Item</h2>
    <%= render 'item_form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingListApp</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'New List', new_shopping_list_path %></li>
      </ul>
    </div>
  </nav>
  
  <%= yield %>

</body>
</html>

app/views/shopping_lists/_form.html.erb
<%= form_for @shopping_list do |f| %>
 
  <% if @shopping_list.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@shopping_list.errors.count, "error") %> prohibited
        this list from being saved:
      </h2>
      <ul>
        <% @shopping_list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/shopping_lists/edit.html.erb
<div class="container">
    <h2>Edit List</h2>
    <%= render 'form' %>
</div>

app/views/shopping_lists/index.html.erb
<div class="container list-counter">
    <h2>You have <%= @shopping_lists.count %> shopping lists</h2>
</div>

<div class="container">
    <% @shopping_lists.each do |shopping_list| %>
        <div class="container list-container col-sm-10 col-md-4 col-lg-3">
            <h2><%= shopping_list.name %></h2>
            <p class="list-description"><%= shopping_list.description %></p>
            <ul>
                
                <% items = shopping_list.items %>
                
                <%= "<h4>List:</h4>".html_safe if items.any? %>
                
                <% items.each do |item| %>
                    <li><%= item.quantity %> <%= item.name %></li>
                <% end %>
                
            
            </ul>
            <ul class="nav nav-tabs nav-justified">
                <li><%= link_to 'Show', shopping_list_path(shopping_list) %></li>
                <li><%= link_to 'Edit', edit_shopping_list_path(shopping_list) %></li>
                <li><%= link_to 'Delete', shopping_list_path(shopping_list),
                       method: :delete,
                       data: { confirm: 'Are you sure about this?' }%></li>
            </ul>
        </div>
    <% end %>
</div>

app/views/shopping_lists/new.html.erb
<div class="container">
    <h2>New List</h2>
    <%= render 'form' %>
</div>

app/views/shopping_lists/show.html.erb
<div class="container">
  <h2><%= @shopping_list.name %></h2>
  <p class="list-description"><%= @shopping_list.description %></p>
  <% items = @shopping_list.items %>
  <h4>List:</h4>
  <% if !items.any? %>
    <%= "<p>-empty-</p>".html_safe %>
  <% else %>
    <ul>
      <% items.each do |item| %>
        <li><%= item.quantity %> <%= item.name %> <%= link_to 'Remove', shopping_list_item_path(@shopping_list, item), method: :delete, data: { confirm: 'Are you sure about this?' } %></li>
      <% end %>
    </ul>
  <% end %>
  <p class="add-item-button"><%= link_to 'Add Item', new_shopping_list_item_path(@shopping_list) %></p>

</div>

<div class="container">
  <p><%= %></p>
</div>